import { APP_URL, CLOUD_URL } from './constants.js'

export function recoveryPage(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Hulala Local</title>
<style>
:root{color-scheme:light dark;font:15px/1.5 system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:Canvas;color:CanvasText}.env{position:fixed;top:16px;left:16px;display:flex;gap:6px;padding:5px;border:1px solid color-mix(in srgb,CanvasText 14%,transparent);border-radius:12px;background:Canvas;box-shadow:0 8px 32px #0002}.env a,.env span{padding:6px 10px;border-radius:8px;text-decoration:none;color:inherit}.env span{background:#246bfd;color:#fff}.card{width:min(580px,calc(100% - 32px));margin:auto;padding:32px;border:1px solid color-mix(in srgb,CanvasText 14%,transparent);border-radius:20px;box-shadow:0 18px 60px #0002}main{min-height:100vh;display:grid;place-items:center;padding:80px 0 32px}h1{margin:0 0 8px;font-size:28px}p{color:color-mix(in srgb,CanvasText 68%,transparent)}.status{display:flex;align-items:center;gap:8px;margin:22px 0}.dot{width:9px;height:9px;border-radius:50%;background:#d49b00}.dot.running{background:#24a35a}.actions{display:flex;gap:10px;flex-wrap:wrap}button{border:0;border-radius:10px;padding:11px 16px;background:#246bfd;color:white;font:inherit;cursor:pointer}button.secondary{background:color-mix(in srgb,CanvasText 8%,transparent);color:inherit}button:disabled{opacity:.55;cursor:wait}.detail{margin-top:18px;font:12px ui-monospace,SFMono-Regular,monospace;color:color-mix(in srgb,CanvasText 58%,transparent)}
</style></head><body>
<nav class="env" aria-label="Environment"><span>Local</span><a href="${CLOUD_URL}" target="_blank" rel="noreferrer">Cloud ↗</a></nav>
<main><section class="card"><h1>Hulala Local</h1><p>The lightweight launcher is running. Start the AI workbench here without returning to the terminal.</p><div class="status"><i class="dot" data-dot></i><strong data-status>Connecting…</strong></div><div class="actions"><button data-start>Start workbench</button><button class="secondary" data-restart>Restart</button><button class="secondary" data-autostart hidden>Enable start after login</button><button class="secondary" data-update hidden>Update</button></div><div class="detail" data-detail>${APP_URL}</div></section></main>
<script>
let token='';let busy=false;
const statusEl=document.querySelector('[data-status]'),detail=document.querySelector('[data-detail]'),dot=document.querySelector('[data-dot]');
async function load(){try{const r=await fetch('/api/hulala/service',{cache:'no-store'});const v=await r.json();token=v.actionToken;const w=v.workbench;statusEl.textContent=w.state[0].toUpperCase()+w.state.slice(1);detail.textContent=(w.pid?'PID '+w.pid+' · ':'')+'Version '+w.version;dot.classList.toggle('running',w.state==='running');document.querySelector('[data-autostart]').hidden=!v.autostart?.supported||v.autostart?.installed;const update=document.querySelector('[data-update]');update.hidden=!v.update?.available||!v.autostart?.installed;update.textContent=v.update?.latestVersion?'Update to v'+v.update.latestVersion:'Update';if(w.state==='running'&&!busy)location.reload()}catch{statusEl.textContent='Launcher connection interrupted'}}
async function action(name){busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await fetch('/api/hulala/service',{method:'POST',headers:{'content-type':'application/json','x-hulala-token':token},body:JSON.stringify({action:name})});const v=await r.json();if(!r.ok)throw new Error(v.error||'Request failed');location.reload()}catch(e){statusEl.textContent=e.message;busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false)}}
document.querySelector('[data-start]').onclick=()=>action('start');document.querySelector('[data-restart]').onclick=()=>action('restart');document.querySelector('[data-autostart]').onclick=()=>action('autostart-install');document.querySelector('[data-update]').onclick=()=>{if(confirm('Install the latest Hulala version and restart Local?'))action('update')};load();setInterval(load,1500);
</script></body></html>`
}
